In [41]:
import numpy as np

masked_test = np.arange(1,19).reshape(2,3,3)
display(masked_test)

mask = np.zeros(9)
mask[::2] = 1
mask1 = mask.reshape(3,3)

mask = np.zeros(9)
mask[1::2] = 1
mask2 = mask.reshape(3,3)

stacked_mask = np.stack((mask1, mask2))
display(stacked_mask)

# Mask needs to be duplicated
masked_test = np.ma.masked_array(masked_test, stacked_mask)

masked_test

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

array([[[1., 0., 1.],
        [0., 1., 0.],
        [1., 0., 1.]],

       [[0., 1., 0.],
        [1., 0., 1.],
        [0., 1., 0.]]])

masked_array(
  data=[[[--, 2, --],
         [4, --, 6],
         [--, 8, --]],

        [[10, --, 12],
         [--, 14, --],
         [16, --, 18]]],
  mask=[[[ True, False,  True],
         [False,  True, False],
         [ True, False,  True]],

        [[False,  True, False],
         [ True, False,  True],
         [False,  True, False]]],
  fill_value=999999)

In [42]:
fill_array = np.random.randint(1, 9, 18).reshape(2, 3,3)

fill_mask = np.zeros(9).reshape(3,3)
fill_mask[:2, :2] = 1
fill_mask = np.stack((fill_mask, fill_mask))

masked_fill_array = np.ma.masked_array(fill_array, fill_mask)

# masked_fill_array = np.ma.filled(masked_fill_array.astype(np.float32), fill_value = np.nan)

masked_fill_array

masked_array(
  data=[[[--, --, 7],
         [--, --, 3],
         [3, 7, 8]],

        [[--, --, 8],
         [--, --, 2],
         [2, 5, 5]]],
  mask=[[[ True,  True, False],
         [ True,  True, False],
         [False, False, False]],

        [[ True,  True, False],
         [ True,  True, False],
         [False, False, False]]],
  fill_value=999999)

In [44]:
print("masked_test:\n", masked_test)
print()
print("masked_fill_array:\n", masked_fill_array)
print()

result = np.ma.filled(masked_test.astype(np.float32), 
                      np.ma.filled(masked_fill_array.astype(np.float32), fill_value = np.nan)
                     )

result

masked_test:
 [[[-- 2 --]
  [4 -- 6]
  [-- 8 --]]

 [[10 -- 12]
  [-- 14 --]
  [16 -- 18]]]

masked_fill_array:
 [[[-- -- 7]
  [-- -- 3]
  [3 7 8]]

 [[-- -- 8]
  [-- -- 2]
  [2 5 5]]]



array([[[nan,  2.,  7.],
        [ 4., nan,  6.],
        [ 3.,  8.,  8.]],

       [[10., nan, 12.],
        [nan, 14.,  2.],
        [16.,  5., 18.]]], dtype=float32)

In [39]:
print("masked_test:\n", masked_test)
print()
print("masked_fill_array:\n", masked_fill_array)
print()
# Note that 
result = np.ma.filled(masked_test.astype(np.float32), masked_fill_array)
print(result)

masked_test:
 [[[-- 2 --]
  [4 -- 6]
  [-- 8 --]]

 [[10 -- 12]
  [-- 14 --]
  [16 -- 18]]]

masked_fill_array:
 [[[nan nan  6.]
  [nan nan  3.]
  [ 2.  7.  6.]]

 [[nan nan  8.]
  [nan nan  7.]
  [ 4.  2.  7.]]]

[[[nan  2.  6.]
  [ 4. nan  6.]
  [ 2.  8.  6.]]

 [[10. nan 12.]
  [nan 14.  7.]
  [16.  2. 18.]]]


In [40]:
result_mask = np.isnan(result)

result = np.ma.masked_array(result, result_mask)

result

masked_array(
  data=[[[--, 2.0, 6.0],
         [4.0, --, 6.0],
         [2.0, 8.0, 6.0]],

        [[10.0, --, 12.0],
         [--, 14.0, 7.0],
         [16.0, 2.0, 18.0]]],
  mask=[[[ True, False, False],
         [False,  True, False],
         [False, False, False]],

        [[False,  True, False],
         [ True, False, False],
         [False, False, False]]],
  fill_value=1e+20,
  dtype=float32)

In [18]:
# Impute missing values in the masked array with values from the replacement array
# this works - use this method to fill clouds
imputed_array = np.ma.filled(masked_test, masked_fill_array)

imputed_array

array([[[ 6,  2,  3],
        [ 4,  1,  6],
        [ 6,  8,  8]],

       [[10,  8, 12],
        [ 5, 14,  8],
        [16,  8, 18]]])

In [24]:
import numpy as np

# Create two masked arrays a and b (replace these with your data)
a = np.ma.masked_invalid([[1, 2, np.nan], [4, np.nan, 6], [7, 8, np.nan]])
b = np.ma.masked_invalid([[9, 10, np.nan], [11, 12, np.nan], [13, 14, 15]])

# Create a new array where missing data in a is filled by data in b
result = np.ma.filled(a, b)

print(a)
print()
print(b)
print()
# Print the resulting array
print(result)

[[1.0 2.0 --]
 [4.0 -- 6.0]
 [7.0 8.0 --]]

[[9.0 10.0 --]
 [11.0 12.0 --]
 [13.0 14.0 15.0]]

[[ 1.  2. nan]
 [ 4. 12.  6.]
 [ 7.  8. 15.]]


In [31]:
print("masked_test:\n", masked_test)
print()
print("masked_fill_array:\n", masked_fill_array)
print()
# Note that 
result = np.ma.filled(masked_test, masked_fill_array)
print(result)

masked_test:
 [[[-- 2 --]
  [4 -- 6]
  [-- 8 --]]

 [[10 -- 12]
  [-- 14 --]
  [16 -- 18]]]

masked_fill_array:
 [[[-- -- 3]
  [-- -- 4]
  [6 6 8]]

 [[-- -- 3]
  [-- -- 8]
  [8 8 8]]]

[[[ 6  2  3]
  [ 4  1  6]
  [ 6  8  8]]

 [[10  8 12]
  [ 5 14  8]
  [16  8 18]]]


In [29]:
a

masked_array(
  data=[[1.0, 2.0, --],
        [4.0, --, 6.0],
        [7.0, 8.0, --]],
  mask=[[False, False,  True],
        [False,  True, False],
        [False, False,  True]],
  fill_value=1e+20)